### ISSUE TITLE
Кастомные ошибки для ModelNotFoundException

### ISSUE THREAD

**Issue by Romik90** [adelf/acwa_book_ru#23]
В главе про обработку ошибок я так и не понял одну вещь. Допустим ситуация такая: я ищу запись в бд, и не нахожу ее. В зависимости от вида модели я хочу отправить клиенту сообщение об ошибке. 
В контроллере у меня так 
`$promocode = Promocode::where('code', $request->promocode)->firstOrFail();`

в случае если это аякс запрос, я хочу вернуть ответ в универсальном для меня формате. Для этого в handler.php в методе render я пишу следующее
![image](https://user-images.githubusercontent.com/17782452/78126237-e77e3080-741a-11ea-8674-ef5d194f30ce.png)

Проблема тут в том, что я не могу из контроллера передать нужное мне сообщение об ошибке. Что тут можно сделать?

**Comment by Romik90** [comment]
Пока что приходится писать вот так в контроллере
![image](https://user-images.githubusercontent.com/17782452/78128396-86585c00-741e-11ea-811b-d325a58b9c9c.png)

**Comment by adelf** [comment]
Привет. То, что приходится писать как выше - нормально. Когда мы обрабатываем URL вида `/user/42` мы не ожидаем, что юзера с таким id не окажется. Мы всё-таки держим в уме, что такой юзер есть. и делаем findOrFail. в случае же промокода, у нас такой уверенности нет, его вводит юзер, он может ошибиться. И лакмусовой бумажкой на то, что мы ожидаем это, является отдельное сообщение "такой промокод не существует". Так что совершенно верный вариант.

**Comment by Romik90** [comment]
Спасибо за ответ!
