### ISSUE TITLE
Выборка по двум полям

### ISSUE THREAD

**Issue by Romik90** [adelf/acwa_book_ru#24]
Пишу простую аналитику для данных их crm системы. У меня есть 2 сущности: сделка Lead, и менеджер Responsible, который с этой сделкой работает. Для аналитики мне нужно сделать несколько выборок. Одна из них это получение по менеджеру сделок в статусе Оплачено, и в статусе Ожидает оплату
![image](https://user-images.githubusercontent.com/17782452/80390890-b8da6500-88b5-11ea-9eae-c775c35ca821.png)

При этом приходится дублировать код в модели Responsible
![image](https://user-images.githubusercontent.com/17782452/80391188-140c5780-88b6-11ea-8890-9ab9ac784195.png)
Приходится это делать из-за того, что в eager load нельзя использовать алиасы 
![image](https://user-images.githubusercontent.com/17782452/80391545-8aa95500-88b6-11ea-880e-c3a3e7c61d19.png)
Вот так к сожалению не работает. Как не дублировать код я так и не нашел способа, может вы что-то подскажете?

И вторая проблема с елоквентом. Структура таблицы leads такая, что связка с ответственным менеджером может быть как по полю responsible_id, так и по полю extra_responsible. Запрос на выборку сделок выглядит так:
![image](https://user-images.githubusercontent.com/17782452/80392225-89c4f300-88b7-11ea-9efb-f935f02b95bc.png)
Как такой запрос сделать в елоквенте, я не представляю. Да, можно было бы решить через отношение многие-ко многим, но сейчас структуру базы данных я менять не готов. Есть ли какой-то другой выход?

**Comment by adelf** [comment]
не надо такие запросы делать в элоквенте. надо делать обычные SQL и данные хоть в массивах получать и использовать.
