### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by stul337** [adelf/acwa_book_ru#48]
Файл и раздел - https://github.com/adelf/acwa_book_ru/blob/master/manuscript/8-unit-test.md#%D0%BC%D0%BE%D0%BA%D0%B8-laravel-%D1%84%D0%B0%D1%81%D0%B0%D0%B4%D0%BE%D0%B2

![изображение](https://github.com/adelf/acwa_book_ru/assets/58220335/6e9dcece-e0eb-4623-924a-b15c4f2ef9ed)

**Comment by adelf** [comment]
fixed. thx.
