### ISSUE TITLE
Зачем избыточный метод авторизации в FormRequest`ах?

### ISSUE THREAD

**Issue by jdeeline** [adelf/acwa_book_ru#53]
В главе "Слой приложения", раздел "Передача данных запроса" есть такое [предложение](https://github.com/adelf/acwa_book_ru/blob/master/manuscript/4-application-layer.md?plain=1#L336):

> В моих проектах всегда есть базовый FormRequest класс, в котором метод authorize с одним оператором return true;, который позволяет забыть про авторизацию на этом уровне.

А зачем? В классе Illuminate\Foundation\Http\FormRequest проверяется существование метода authorize, и в случае его отсутствия считается, что авторизация пройдена (там тот же оператор return true). Можно просто не включать этот метод в свои классы.

**Comment by adelf** [comment]
Когда писал была версия 5.* какаято. там надо было. В любом случае, удалил это. Спасибо.
